
services:
  postgres:
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "25430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    entrypoint: /bin/bash -c
    command:
      - ". start_local.sh"
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8001:8001"

volumes:
  postgres-data:
