# Generated by Django 5.1.4 on 2024-12-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["name"],
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства",
            },
        ),
        migrations.AlterModelOptions(
            name="devicemodel",
            options={
                "ordering": ["name"],
                "verbose_name": "Модель устройства",
                "verbose_name_plural": "Модели устройств",
            },
        ),
    ]
