# Generated by Django 5.1.4 on 2024-12-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
